use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :core, Core.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: "core.gigalixirapp.com", port: 4000],
  check_origin: [
    "https://core.gigalixirapp.com",
    "https://now.brandnewcongress.org",
    "https://www.brandnewcongress.org",
    "https://brandnewcongress.org",
    "https://now.justicedemocrats.com",
    "https://www.justicedemocrats.com",
    "https://justicedemocrats.com",
    "http://localhost:4000"
  ],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/manifest.json",
  server: true

import_config "prod.secret.exs"
